
version: "3.3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres
  app:
    container_name: nestjs-tutorial
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/lynx/src/nestjs-tutorial
      - /lynx/src/nestjs-tutorial/node_modules
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge